// @flow

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';
export const RESET_SEARCH_KEY = 'RESET_SEARCH_KEY';
