export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS = 'FETCH_POSTS';

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';
export const RESET_SEARCH_KEY = 'RESET_SEARCH_KEY';
